export const appConfig = {
  name: "白黒つけない会議",
  roomName: "",
  communityName: "",
  defaultRoomId: "main",
  rooms: [
    {
      id: "main",
      name: "メイン会場",
      description: "標準の会議ルーム",
    },
  ],
  speakerName: "今話している人",
  speakerAvatarInitial: "話",
  maxSpeakers: 5,
  speakerPalette: ["#47b8ff", "#8f7cff", "#f3d26f", "#ff6b9a", "#7dd3fc"],
  realtimeStatusLabel: "ローカル試作中",
  access: {
    hostKey: "host-demo",
    speakerKey: "speaker-demo",
    hostUnlockedByDefault: false,
    speakerUnlockedByDefault: true,
    speakerControlEnabledByDefault: true,
  },
  meter: {
    startAngle: 165,
    endAngle: 375,
    centerX: 260,
    centerY: 260,
    radius: 190,
    speakerRadiusOffsets: [-24, -12, 0, 12, 24],
    animationMs: 420,
  },
  sound: {
    enabledByDefault: true,
    tickStep: 5,
    minIntervalMs: 72,
    volume: 0.022,
  },
  sync: {
    fallbackRefreshIntervalMs: 7000,
    localEditQuietMs: 1800,
  },
  colors: {
    left: "#47b8ff",
    middle: "#f3d26f",
    right: "#ff6b9a",
    violet: "#8f7cff",
  },
} as const;
